name: AIOLint - All-in-One Linter

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip3 install pylint flake8 black isort
          npm install -g eslint prettier
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          composer global require squizlabs/php_codesniffer friendsofphp/php-cs-fixer
          sudo apt install cppcheck shellcheck shfmt
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Setup Rust
        run: |
          rustup update
          rustup component add rustfmt clippy

      - name: Check & Fix Code Formatting
        run: |
          black .
          isort .
          eslint . --fix || true
          golangci-lint run || true
          phpcs --standard=PSR12 . || true
          cargo fmt || true
          cargo clippy || true
          cppcheck . || true
          hadolint Dockerfile || true

      - name: Run AIOLint
        run: python3 scripts/lint_checker.py

      - name: Automatic Repair (Optional)
        if: success() || failure()
        run: python scripts/fix_code.py
