name: AIOLint - All-in-One Linter

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip3 install pylint flake8 black isort
          npm install -g eslint prettier
          go install golang.org/x/tools/cmd/goimports@latest
          composer global require squizlabs/php_codesniffer
          sudo apt install cppcheck shellcheck

      - name: Install rustfmt if you don't have it yet
        run: |
          if ! command -v cargo-fmt &> /dev/null; then
            cargo install rustfmt
          else
            echo "rustfmt is already installed, past the installation .."
          fi

      - name: Run AIOLint
        run: python3 scripts/lint_checker.py

      - name: Automatic Repair (Optional)
        if: success() || failure()
        run: python scripts/fix_code.py
